# Generated by Django 5.2.1 on 2025-05-20 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="class",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
