# Generated by Django 5.2.1 on 2025-05-20 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0002_alter_class_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="classsubject",
            name="quantity",
            field=models.IntegerField(default=1),
        ),
    ]
