# Generated by Django 5.2.1 on 2025-05-20 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0003_classsubject_quantity"),
    ]

    operations = [
        migrations.RenameField(
            model_name="classsubject",
            old_name="quantity",
            new_name="maximum_per_week",
        ),
    ]
