# Generated by Django 5.2.1 on 2025-05-21 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0005_faculty"),
    ]

    operations = [
        migrations.AddField(
            model_name="class",
            name="faculty",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="schedule.faculty",
            ),
            preserve_default=False,
        ),
    ]
