# Generated by Django 5.2.1 on 2025-05-25 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0006_class_faculty"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="class",
            options={"ordering": ["name"], "verbose_name_plural": "Classes"},
        ),
        migrations.AlterModelOptions(
            name="faculty",
            options={"ordering": ["name"], "verbose_name_plural": "Faculties"},
        ),
        migrations.AlterModelOptions(
            name="teacherunavailabletime",
            options={"verbose_name_plural": "Teacher Unavailable Times"},
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("json_data", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "generated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
