# Generated by Django 5.2.1 on 2025-06-05 13:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0009_teacherunavailableslot"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="teacherunavailableslot",
            constraint=models.UniqueConstraint(
                fields=("teacher", "day", "lesson_number"),
                name="unique_teacher_day_lesson",
            ),
        ),
    ]
