# Generated by Django 5.2.1 on 2025-06-18 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0010_teacherunavailableslot_unique_teacher_day_lesson"),
    ]

    operations = [
        migrations.CreateModel(
            name="Auditory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=10, unique=True)),
            ],
        ),
    ]
