# Generated by Django 5.2.1 on 2025-05-19 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
